"""create users table

Revision ID: ee5943b1c37d
Revises: ab160158f8aa
Create Date: 2025-04-25 19:23:50.440104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee5943b1c37d'
down_revision: Union[str, None] = 'ab160158f8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('user_id', sa.String(), nullable=True))
    op.alter_column('holdings', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_holdings_user_id'), 'holdings', ['user_id'], unique=False)
    op.add_column('watchlist', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_watchlist_user_id'), 'watchlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_user_id'), table_name='watchlist')
    op.drop_column('watchlist', 'user_id')
    op.drop_index(op.f('ix_holdings_user_id'), table_name='holdings')
    op.alter_column('holdings', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('holdings', 'user_id')
    # ### end Alembic commands ###
